# Series 클래스

In [2]:
import pandas as pd

In [5]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [6]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [7]:
print(s.values)

[1 3 5 7 9]


In [10]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [11]:
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='str')


In [12]:
print(s.values)

[9904312 3448737 2890451 2466052]


In [14]:
s.name = "인구"
s.index.name = "도시"
print(s)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [15]:
s.index.name = None
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [16]:
print(pd.Series(range(1, 5)))

0    1
1    2
2    3
3    4
dtype: int64


In [17]:
s = pd.Series(['samsung', 81000])
print(s)

0    samsung
1      81000
dtype: object


In [20]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [21]:
data = [1000, 2000, 3000]
s = Series(data)
s.index = ["메로나", "구구콘", "하겐다즈"]
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [32]:
data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [40]:
data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data=data, index=index)
print(s)
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64
메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [38]:
s2 = s2.fillna(0)
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [41]:
price = [42500, 42550, 21800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    21800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [42]:
data = {
    "2019-05-31": 42500,
    "2019-05-30": 42550,
    "2019-05-29": 41800,
    "2019-05-28": 42550,
    "2019-05-27": 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [45]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [46]:
print(s.values)

[42500 42550 41800 42550 42650]


In [50]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index = [1, 2, 3])
s3 = Series([10, 20, 30], index = ['a', 'b', 'c'])

print(s1[1])
print(s2[1])
print(s3['a'])

20
10
10


In [51]:
print(s3.index[0])
print(s3.index[-1])

a
c


In [57]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [58]:
print(s[1:3])

부산    3448737
인천    2890451
dtype: int64


In [59]:
print(s["부산":"대구"])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [68]:
print(s[:-1])

서울    9904312
부산    3448737
인천    2890451
dtype: int64


In [62]:
print(s[:2])

서울    9904312
부산    3448737
dtype: int64


In [72]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [73]:
print("대구" in s)

True


In [75]:
for key, value in s.items():
    print("%s : %d" % (key, value))

서울 : 9904312
부산 : 3448737
인천 : 2890451
대구 : 2466052


In [78]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}, index=["부산", "서울", "인천", "대전"])
print(s2)

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64


In [79]:
from pandas import Series

data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "하겐다즈"]
s = Series(data=data, index=index)
s

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64

In [80]:
print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [81]:
print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [83]:
indice = [0, 2]
print(s.iloc[indice])

메로나     1000
하겐다즈    3000
dtype: int64


In [86]:
indice = ["메로나", "하겐다즈"]
print(s.loc[indice])
print(s.loc[["메로나", "하겐다즈"]])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [88]:
s

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64

In [89]:
s.loc["메로나"] = 500 # s.iloc[0] = 500, s["메로나"] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [90]:
s.loc["비비빅"] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [94]:
s = s.drop("메로나")
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [96]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}, index=["부산", "서울", "인천", "대전"])
ds = s - s2
print(ds)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [97]:
s3 = s / 100000
print(s3)

서울    99.04312
부산    34.48737
인천    28.90451
대구    24.66052
dtype: float64


In [98]:
print(s.values - s2.values)

[ 6511121 -6182745   258416   975894]


In [99]:
print(ds[ds.notnull()])

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [102]:
print(s)
print()
print(s2)
print()
rs = (s - s2) / s2 * 100
print(rs)
print()
rs = rs[rs.notnull()]
print(rs)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [103]:
rs["부산"] = 1.63
rs["대구"] = 1.41
print(rs)

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64


In [104]:
del rs["서울"]
print(rs)

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64


In [105]:
from pandas import Series

date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350], index=date)
print(high)
print('---------------------')
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
---------------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [107]:
diff = high - low
diff

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64

In [112]:
print(diff.idxmax())

6/4


In [113]:
data = {
    "삼성전자": "전기,전자",
    "LG전자": "전기,전자",
    "현대차": "운수장비",
    "NAVER": "서비스업",
    "카카오": "서비스업"
}
s = Series(data)
print(s)

삼성전자     전기,전자
LG전자     전기,전자
현대차       운수장비
NAVER     서비스업
카카오       서비스업
dtype: str


In [114]:
print(s.unique())

<StringArray>
['전기,전자', '운수장비', '서비스업']
Length: 3, dtype: str


In [115]:
print(s.value_counts())

전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64


In [118]:
import pandas as pd
import numpy as np

s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [119]:
s.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [120]:
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [123]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: str

In [139]:
def remove_comma(x):
    print(x, 'in function')
    return int(x.replace(",", ""))

In [140]:
s = Series(["1,234", "5,678", "9,876"])
result = list(s.map(remove_comma))
print(result)

1,234 in function
5,678 in function
9,876 in function
[1234, 5678, 9876]


In [142]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(data=data, index=index)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [143]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [144]:
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [145]:
print(s[s > 42000])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [153]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data=data, index=index)
print(s)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64


In [154]:
s1 = s.sort_values(ascending=False)
print(s1)

000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [157]:
s2 = s.rank(ascending=False)
print(s2)

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64


In [183]:
a = Series(dict(zip([1, 2, 3, 4], ["a", "b", "c", "d"])), [2, 4])
print(a)
print()
print(a.index)
print()
print(a.values)

2    b
4    d
dtype: str

RangeIndex(start=2, stop=6, step=2)

<StringArray>
['b', 'd']
Length: 2, dtype: str
