In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
a = np.array(list1)
a

array([1, 2, 3])

In [3]:
print(a.shape)

(3,)


In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b.shape)

(2, 4)


In [5]:
print(b[0, 0])

1


In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b[1, 2]

np.int64(7)

In [9]:
a = np.array([1, 2.3, 3, 4])
print(a)

[1.  2.3 3.  4. ]


In [10]:
a = np.array([1, '2', '3', 4])
print(a)

['1' '2' '3' '4']


In [11]:
a = np.array([1, 2, '3', 4])
print(a)

['1' '2' '3' '4']


In [12]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a3 = np.array([[[1, 2, 3], [1, 2, 3]],
               [[1, 2, 3], [1, 2, 3]],
               [[1, 2, 3], [1, 2, 3]]])

In [13]:
a1

array([1, 2, 3, 4, 5])

In [14]:
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
a3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [16]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [17]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 4)
(3, 2, 3)


In [18]:
a = np.zeros((3), dtype='int64')
print(a)

[0 0 0]


In [19]:
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [20]:
a = np.zeros((2, 2), dtype='int64')
print(a)

[[0 0]
 [0 0]]


In [21]:
a = np.zeros((2, 2, 2), dtype='int64')
print(a)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [22]:
a = np.ones((3), dtype='int64')
print(a)

[1 1 1]


In [23]:
a = np.ones((3))
print(a)

[1. 1. 1.]


In [24]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
a = np.full((3), 1, dtype='int64')
print(a)

[1 1 1]


In [26]:
a = np.full((3), 10, dtype='int64')
print(a)

[10 10 10]


In [27]:
a = np.full((2, 3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [28]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a = range(0, 10, 2)
print(np.array(a))

[0 2 4 6 8]


In [30]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.array(range(12)).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a = np.arange(12).reshape((3, -1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
a = np.arange(12).reshape((6, -1))
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [36]:
a = np.arange(12).reshape((-1, 3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
lst = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a = arr[0:2, 0:2]
a

array([[1, 2],
       [4, 5]])

In [39]:
a = arr[1:, 1:]
a

array([[5, 6],
       [8, 9]])

In [40]:
a = [0,1,2,3]
b = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

In [41]:
print(a[1:4:2])

[1, 3]


In [42]:
print(a[1:4:2])

[1, 3]


In [43]:
print(a[::-1])

[3, 2, 1, 0]


In [44]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print('-'*10)
print(c)

[0 1 2 3]
----------
[0 1 2 3]


In [45]:
a+c

array([0, 2, 4, 6])

In [46]:
a = [0,1,2,3]
b = [0,1,2,3]
print(a + b)

[0, 1, 2, 3, 0, 1, 2, 3]


In [47]:
d = [0,0,0,0]
for i in range(len(a)):
    d[i] = a[i] + b[i]

print(d)

[0, 2, 4, 6]


In [48]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.split(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [51]:
np.split(a, (1, 3)) # [:1], [1:3], [3:]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [52]:
np.split(a, (1, 3), axis=1) # [:1], [1:3], [3:]

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [53]:
splite1, splite2 = np.hsplit(a, 2)

In [54]:
print("splite1"); print(splite1)

splite1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [55]:
print("splite2"); print(splite2)

splite2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [56]:
splite1, splite2 = np.vsplit(a, 2)

In [57]:
print("splite1"); print(splite1)

splite1
[[0 1 2 3]
 [4 5 6 7]]


In [58]:
print("splite2"); print(splite2)

splite2
[[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
stack0 = np.stack((a,a))
print(stack0.shape)

(2, 4, 4)


In [61]:
print(stack0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [62]:
stack1 = np.stack((a,a), axis=1)
print(stack1.shape)

(4, 2, 4)


In [63]:
print(stack1)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]


In [64]:
print(np.vstack((a,a)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [65]:
print(np.hstack((a,a)))

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


In [66]:
a = np.arange(9).reshape(3,3)
b = 2 * a
print(a)
print('-'*10)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [67]:
print(np.hstack((a,b)))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [68]:
print(np.concatenate((a,b), axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [69]:
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [70]:
print(np.concatenate((a,b),axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [71]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [73]:
c = a.ravel()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [74]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [75]:
c[0] = 100
print(c)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [76]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [77]:
print(a + b)

[5 7 9]


In [78]:
print(np.add(a, b))

[5 7 9]


In [79]:
print(a * b)

[ 4 10 18]


In [80]:
print(np.multiply(a, b))

[ 4 10 18]


In [81]:
lst1 = [[1, 2], [3, 4]]
lst2 = [[1, 2], [3, 4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a, b)
print(c)

[[ 7 10]
 [15 22]]


In [82]:
a = np.array([[1, 2], [3, 4]])
s = np.sum(a, axis=0)
print(s)

[4 6]


In [83]:
s = np.sum(a, axis=1)
print(s)

[3 7]


In [84]:
s = np.prod(a)
print(s)

24


In [85]:
s = np.prod(a, axis=0)
print(s)

[3 8]


In [86]:
s = np.prod(a, axis=1)
print(s)

[ 2 12]


In [87]:
np.random.seed(0)
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [88]:
print(np.random.rand(5))

[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]


In [89]:
x = np.arange(10)
print(x)
print('-'*20)
np.random.seed(0)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
--------------------
[2 8 4 9 1 6 7 3 0 5]


In [90]:
z = np.random.choice(np.arange(5), 3, replace=False)
print(z)

[1 0 2]


In [91]:
z = np.random.choice(5, 50, p=[0.1, 0, 0.3, 0.6, 0])
print(z)

[3 2 3 3 3 3 0 0 0 3 3 3 3 3 3 3 2 3 2 3 3 3 2 3 3 3 0 3 3 3 3 3 2 3 3 0 3
 3 2 2 2 2 3 3 3 2 2 2 3 2]


In [92]:
x = np.random.randint(5, size=5)
print(x)

[4 3 2 0 1]


In [93]:
x = np.random.randint(1, 100, size=5)
print(x)

[70 42 36 65 96]


In [94]:
a = [5, 1, 7, 7, 2, 3, 5]
x = np.unique(a)
print(x)

[1 2 3 5 7]


In [95]:
x, cnt = np.unique(a, return_counts=True)
print(x, cnt, sep=", ")

[1 2 3 5 7], [1 1 1 2 2]


In [96]:
x = [18, 5, 10, 23, 19, -8, 10, 0, 6, 2]
print(len(x))
print(sum(x))
print(np.size(x))
print(np.sum(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.sort(x))

10
85
10
85
8.5
82.05
9.058145505565696
23
-8
8.0
[-8  0  2  5  6 10 10 18 19 23]
